touch files

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,16 +1,15 @@
 name: Reusable publish workflow
 
-
 on:
   workflow_call:
     inputs:
-      version:
+      package_version:
         type: string
         required: true
-      package:
+      package_name:
         type: string
         required: true
-      provider:
+      package_provider:
         type: string
         required: true
       run-test:
@@ -38,11 +37,11 @@ jobs:
       package_registry: ${{ env.PACKAGE_REGISTRY }}
 
     env:
-      PACKAGE_VERSION: ${{ inputs.version }}
+      PACKAGE_VERSION: ${{ inputs.package_version }}
       PACKAGE_REGISTRY: ghcr.io
-      PACKAGE_REPOSITORY: ${{ github.repository }}/${{ inputs.provider }}/crossplane/${{ inputs.package }}
-      PACKAGE_PROVIDER: ${{ inputs.provider }}
-      PACKAGE_NAME: ${{ inputs.package }}
+      PACKAGE_REPOSITORY: ${{ github.repository }}/${{ inputs.package_provider }}/crossplane/${{ inputs.package_name }}
+      PACKAGE_PROVIDER: ${{ inputs.package_provider }}
+      PACKAGE_NAME: ${{ inputs.package_name }}
 
     steps:
 
@@ -51,42 +50,56 @@ jobs:
           env | sort
 
   test:
-    runs-on: ubuntu-latest
+    if: inputs.run-test
+    uses: ./.github/workflows/test.yml
     needs:
       - publish
-    if: inputs.run-test
-    env:
-      CONFIG_VERSION: ${{ inputs.version }}
-      CONFIG_IMAGE: ${{ needs.publish.outputs.package_registry }}/${{ needs.publish.outputs.package_repository }}
+    with:
+      package_version: ${{ inputs.package_version }}
+      package_name: ${{ inputs.package_name }}
+      package_provider: ${{ inputs.package_provider }}
 
-    steps:
+  # test:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - publish
+  #   if: inputs.run-test
+  #   env:
+  #     CONFIG_VERSION: ${{ inputs.package_version }}
+  #     CONFIG_IMAGE: ${{ needs.publish.outputs.package_registry }}/${{ needs.publish.outputs.package_repository }}
 
-      - name: Dump info
-        run: |
-          env | sort
+  #   steps:
 
-      - name: Create k8s Kind Cluster
-        uses: helm/kind-action@v1.4.0
-        with:
-          verbosity: 5
-          version: ${{ inputs.kind-version }}
-          kubectl_version: ${{ inputs.kubernetes-version }}
-          node_image: kindest/node:${{ inputs.kubernetes-version }}
+  #     - name: Dump info
+  #       run: |
+  #         env | sort
 
-      - name: Verify Cluster
-        run: |
-          kubectl version
-          which kubectl
-          kubectl cluster-info
-          kubectl get storageclass standard
+  #     - name: Create k8s Kind Cluster
+  #       uses: helm/kind-action@v1.4.0
+  #       with:
+  #         verbosity: 5
+  #         version: ${{ inputs.kind-version }}
+  #         kubectl_version: ${{ inputs.kubernetes-version }}
+  #         node_image: kindest/node:${{ inputs.kubernetes-version }}
 
-      - name: Test Crossplane MongoDB Package
-        if: inputs.package == 'mongodb'
-        run: |
-          echo ./crossplane-e2e-mongodb.sh
-          exit 1
+  #     - name: Verify Cluster
+  #       run: |
+  #         kubectl version
+  #         which kubectl
+  #         kubectl cluster-info
+  #         kubectl get storageclass standard
 
-      - name: Cleanup MongoDB Package
-        if: always() && inputs.package == 'mongodb'
-        run: |
-          echo ./mongodb/crossplane-e2e-cleanup.sh
+  #     - name: Create Azure Config Secret
+  #       if: inputs.provider == 'azure'
+  #       run: |
+  #         kubectl create namespace upbound-system
+  #         kubectl create secret generic azure-secret -n upbound-system --from-literal=creds='${{ secrets.AZURE_CONFIG }}'
+
+  #     - name: Test Crossplane Package
+  #       run: |
+  #         [ -x ./crossplane-e2e-${{ inputs.package }}.sh ] && ./crossplane-e2e-${{ inputs.package }}.sh
+  #         exit 1
+
+  #     - name: Cleanup Package
+  #       run: |
+  #         [ -x ./${{ inputs.package }}/crossplane-e2e-cleanup.sh ] && ./${{ inputs.package }}/crossplane-e2e-cleanup.sh
